### ISSUE TITLE
Todo list for the CPC paper

### ISSUE THREAD

**Issue by amghr** [csml-beach/deep-bayesian-operator-nets#8]
- [x] details about each experiment: number of epochs, architecture, things that will help the reader replicate the experiment. @amghr 
- [x] readme file on the github with information about the project, code base, notebooks, examples etc. @SakolB 
- [x] #9
- [ ] uncertainty diagrams for the heat eq
- [x] fix log loss graphs, capture mode data at more epochs so the graph is smoother @keelobytes 
- [x] add more writeup 
- [x] white background plots. make one alpha and another one D. @keelobytes 
- [ ] all plots to same aspect ratio
- [x] separate 2d dataset plot and remove legends. @amghr 
- [ ] add license
- [x] kde plot for aplha vs D @amghr 
<img width="557" alt="image" src="https://github.com/user-attachments/assets/2b17e6ce-6f53-4ac7-8404-7872a2cedfcb">

- [x] graphical abstract
- [x] research highlights
- [x] Add missing doi for all references, remove urls except for software
- [x] add graphical abstract to github readme

**Comment by amghr** [comment]
Closing this as this was an old list
